### ISSUE TITLE
Group preservation

### ISSUE THREAD

**Issue by DVLP** [stevinz/three-subdivide#2]
Currently when the input geometry has groups the resulting geometry doesn't have any.

**Comment by stevinz** [comment]
Okay, I have implemented group handling for both the subdivision and edge splitting functions.

I have updated the library to v1.1.1. The changes can be visualized on the [Examples](https://stevinz.github.io/three-subdivide/LoopSubdivision.html) page by selecting Box, Cone, or Cylinder and cycling `split` on/off. These examples now use grouped geometry and materials for their respective sides.

I don't know your intended use case, but I would appreciate any feedback as to if these changes are working for you as well.
