### ISSUE TITLE
Can't smooth mesh

### ISSUE THREAD

**Issue by destlaver** [stevinz/three-subdivide#4]
No matter what I do, I wasn't able to obtain a smooth surface after the modifier was applied. I tried with a new mesh, with computeVertexNormal(). Nothing works

**Comment by stevinz** [comment]
Smooth surfaces (i.e. smooth vs flat shading) require averaged normals.

Before being subdivided, the geometry is converted to non indexed. As such the resulting normals are calculated per triangle (i.e. flat). It should be possible to obtain smooth surface normals by converting the geometry back to indexed (using [`BufferGeometryUtils.mergeVertices()`](https://github.com/mrdoob/three.js/blob/d10ce505d46e2a72eae662952d6a2d0cf8d8d9e6/examples/jsm/utils/BufferGeometryUtils.js#L575) before running `computeVertexNormal()`. See [this thread](https://discourse.threejs.org/t/buffergeometry-toindexed/1334) for similar discussion.
